blank_issues_enabled: false
contact_links:
    - name: ðŸ’¬ Questions or discussion
      url: https://sanoma.slack.com/archives/C03SA9HUUA3
      about: Please post general questions or discussion topics in our Slack channel.
